### ISSUE TITLE
write ajax methods

### ISSUE THREAD

**Issue by majeeddl** [sdaliri/Jquery-tutorial#11]
please follow steps : 
1.install  node js
2. pull project
3. run command in project folder : "npm install"
4. create file with name of "jquery_ajax.html" in project directory
5 .write get and post method in this file (  contact to me about methods   )
6 . run command : "npm run start"
7 . open url in your browser : "http://localhost:8080"

**Comment by sdaliri** [comment]
سلام من در مرحله پنجم از دستور العمل شما هستم نیاز به کمک شما  در مورد نحوه نوشتن متد های get  و post

دارم
